name: Run Python Scripts

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8' # 根据需要选择Python版本

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Run MD_Converter.py
      run: |
        python path/to/parent/folder/MD_Converter.py

    - name: Run SUMMARY_Generator.py
      run: |
        python path/to/parent/folder/SUMMARY_Generator.py
